### ISSUE TITLE
all command doesn't display quotes

### ISSUE THREAD

**Issue by rikachan58** [TheSchwa/sibyl#26]
Sibyl will drop quotes ("") when returning the message for the all command. When a user uses quotes, the message is the same, sans quotes.

**Comment by TheSchwa** [comment]
Same thing as on the command line, sibyl does quote blocking by default and passes commands a list of arguments; currently `all` is just re-combining the list of args which does lose quotes.

Technically plugins could switch to `mess.get_text()` but that would still have `sibyl all` or whatever in the beginning. I think the best solution here is to add another flag to the `@botcmd` decorator so that commands can request the original, unedited text with command invocation removed.
